### ISSUE TITLE
Magento 2.3: «Df\Sentry\Breadcrumbs\MonologHandler: Incompatible argument type: Required type: \Monolog\Handler\Boolean. Actual type: \Df\Sentry\Breadcrumbs\Boolean» on «bin/magento setup:di:compile»

### ISSUE THREAD

**Issue by dmitry-fedyuk** [mage2pro/core#19]
![01](https://user-images.githubusercontent.com/83204/29097785-582d809a-7ca4-11e7-9627-ab5172b69702.png)

**Comment by dmitry-fedyuk** [comment]
Fixed in [2.10.9](https://github.com/mage2pro/core/releases/tag/2.10.9).

**Comment by scottw-finao** [comment]
ran composer require mage2pro/core "^2.10.9"
it installed 2.12.39

Still getting the error

(in magento 2.2.4)

**Comment by dmitry-fedyuk** [comment]
Always use the latest versions of the mage2pro packages.

**Comment by scottw-finao** [comment]
ummm ok, and if composer update doesn't install them, then what?

**Comment by scottw-finao** [comment]
completely uninstalled mage2pro/core - removed entry from composer.json, made sure folder did not exist in vendor/mage2pro

Re-ran install:
[scottw@daniel magento]$ nano composer.json 
[scottw@daniel magento]$ cd vendor/
[scottw@daniel vendor]$ sudo rm -fr mage2pro
[scottw@daniel vendor]$ cd ..
[scottw@daniel magento]$ sudo -u apache composer require mage2pro/core
Using version ^3.10 for mage2pro/core
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing mage2pro/core (3.10.6): Loading from cache


Still getting the same error

**Comment by dmitry-fedyuk** [comment]
Provide exact screenshot of the error.

**Comment by scottw-finao** [comment]
commend edited

**Comment by scottw-finao** [comment]
I note there are newer versions of the Df_Oauth and Df_Sentry available. Should I force those to a newer version also?

**Comment by dmitry-fedyuk** [comment]
You are wrong: `Df_Sentry` is a part of `mage2pro/core`.

**Comment by scottw-finao** [comment]
ok, well it's showing almost all my Df_* modules as version 1.0.0 - I have another system I was trying to test the magento updates and I notice some of those have v3.* in some of the Df_ prefix modules. Should I try removing any of those before re-installing?

**Comment by scottw-finao** [comment]
Tried removing with composer (composer remove mage2pro/core) then re-ran require and composer install && composer upgrade. Still getting the same error.

**Comment by dmitry-fedyuk** [comment]
I can fix this particular problem for **$150**.
I can upgrade Magento from **2.2.4** to **2.2.6** for **$390**: [mage2.pro/t/4644](https://mage2.pro/t/4644)
I do not want to support or comment any crazy hacks and custom actions for the previously working `mage2pro/core` package.

**Comment by scottw-finao** [comment]
lol, I can upgrade magento with a single command. Are you suggesting that my mage2pro modules will not work until I upgrade magento?

**Comment by dmitry-fedyuk** [comment]
Banned.

**Comment by treii28** [comment]
This solves the problem:

mage2pro/core/Sentry/Breadcrumbs/MonologHandler.php
50c50
<         parent::__construct($level, $bubble);
---
>         parent::__construct($level, boolval($bubble));

**Comment by treii28** [comment]
OK, I see the problem now - that above should 'trick' the dependency injector with your current phpdoc entry, but the problem I was getting is as a result of my actually 'being' on the latest version of the magento libraries. Namely, Seldaek updated his code to fix the problem which means your work-around is now triggering the error as the dependency injector goes over the code. (i.e. if the Bug still exists, your code was working fine)

Try adding a dependency in your packagist to require v1.24.0 or better of the monolog/monolog then remove your extra workaround in the phpdoc on line 46 for an actual hard fix.  At that point, the 'boolval()' is extraneous. But leaving it in shouldn't hurt anything and would make it still work on the old (broken) versions of monolog/monolog

change:
     * @param \Monolog\Handler\Boolean|bool $bubble
back to:
     * @param bool $bubble

When using monolog/monolog v1.24.0 or greater (where Seldaek fixed his bug)
